# this is the github pages configuration file 
tile: CRCP 3320 Notes - Fall 2024 
description: Notes Site for CRCP 3320 for Fall 2024 term.

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme